### ISSUE TITLE
How to show a splash screen first?

### ISSUE THREAD

**Issue by hexdecimal16** [kanzitelli/expo-starter#13]
Is there a guide to show how to add screens.

**Comment by kanzitelli** [comment]
@hexdecimal16 there is no guide at the moment but the screens/stacks setup happens in one file `src/screens/index.ts` where you define options for screens, tabs and modals if needed.

If you want to hide/show splash screen, you can find the relevant code in `App.tsx`.

**Comment by hexdecimal16** [comment]
ok thanks
