### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0)

### ISSUE THREAD

**Issue by vitorcalvi** [kanzitelli/expo-starter#24]
When try to change the UI > Language > Sysytem ----> English
in Expo run:ios -d  (Device Xxxx)
It doesn't work, just in IOS Simulator

[Unhandled promise rejection: Error: You cannot use the Updates module in development mode in a production app. To test manual updates, make a release build with `npm run ios --configuration Release` or `npm run android --variant Release`.]
at http://192.168.1.13:8081/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:102793:321 in _createSuperInternal
at node_modules/expo-modules-core/build/errors/CodedError.js:10:8 in constructor
at http://192.168.1.13:8081/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:233273:49 in reloadAsync$
at node_modules/expo-updates/build/Updates.js:88:7 in reloadAsync
at src/services/navigation/index.ts:40:12 in Nav#restart
at src/services/navigation/index.ts:40:12 in Nav#restart
at src/stores/ui.ts:39:9 in UIStore#setLanguage
at node_modules/mobx/dist/mobx.esm.js:1255:11 in executeAction
at node_modules/mobx/dist/mobx.esm.js:1239:24 in res
at src/screens/settings.tsx:51:53 in <anonymous>
at node_modules/react-native-ui-lib/src/components/actionSheet/index.js:125:4 in ActionSheet#onOptionPress

**Comment by kanzitelli** [comment]
@vitorcalvi it’s related to reloadAsync method from expo-updates module that is not working on simulator.
