### ISSUE TITLE
ApiV2Error: Entity Not Authorized

### ISSUE THREAD

**Issue by venelinn** [kanzitelli/expo-starter#26]
Hello, 
I'm using Manual mode to run this starter but I'm getting this message after iOS simulator opens.
`ApiV2Error: Entity Not Authorized`
iOS 16 with iPhone 14 and 14 Pro Max
MacOS & XCode: Latest

**Comment by kanzitelli** [comment]
Hi @venelinn!

Could you provide more details on that? Do you get the error in terminal or simulator? After which moment is it shown?

The only thing that comes to my mind is to remove EAS config from app.json (updates.url, extra) and eas.json. Maybe it’s trying to download an update tied to my project and account in Expo.dev.

**Comment by kanzitelli** [comment]
@venelinn great! thanks for testing and opening the issue!

EAS config was removed in 4.0.1 as it should be unique per project and can be generated by `eas update:config` ([EAS Update docs](https://docs.expo.dev/eas-update/getting-started/).
