### ISSUE TITLE
Deep linking support

### ISSUE THREAD

**Issue by ssk-mps** [kanzitelli/expo-starter#29]
Thank you for creating this fantastic resource! 🙏 

In my codebase, I have something like this for deep linking
```
import { NavigationContainer } from '@react-navigation/native';

function App() {
  const linking = {
    prefixes: ['https://mychat.com', 'mychat://'],
    config: {
      screens: {
        Home: 'feed/:sort',
      },
    },
  };

  return (
    <NavigationContainer linking={linking} fallback={<Text>Loading...</Text>}>
      {/* content */}
    </NavigationContainer>
  );
}
```

With the latest version of expo-started, I noticed that it is using a rn-navio library. But there is no way to provide custom linking prop. This is very crucial for production apps.

https://reactnavigation.org/docs/navigation-container/#linking
https://docs.expo.dev/guides/deep-linking/

**Comment by kanzitelli** [comment]
Hi @ssk-mps! Thank you!

And yes, you can achieve it with `rn-navio` as it's fully built on React Navigation. Once you built your layout with `const navio = Navio.build(...)`, you can generate `<navio.Root />` component which takes two arguments `initialRouteName` and `navigationContainerProps`. The latter will be passed directly to `NavigationContainer`. In your case, it's going to be something like `<navio.Root navigationContainerProps={{linking: yourLinkings}} />` ([as here](https://github.com/kanzitelli/expo-starter/blob/master/App.tsx#L46), AppRoot == navio.Root).

**Comment by kanzitelli** [comment]
hey @ssk-mps! Glad it helped! And definitely, I am collecting some feedback and feature requests that will be implemented in the next releases.

Could you elaborate more on that and give broader example with use cases? That would be helpful as I don't fully get it.

**Comment by kanzitelli** [comment]
@ssk-mps ah okay, got it! so currently `rn-navio` doesn't provide a type that describes the structure of the app, `RootStackParamList` in your case. maybe I'll come up with something in the future. I will add it into README as well, but now you will need to define it yourself as you do. the structure that navio builds might look like this:

```tsx
const navio = Navio.build({
  screens: {
    Main,
    Settings,
    Example,
    Playground,
  },
  stacks: {
    MainStack: ['Main', 'Example'],
    ExampleModalStack: ['Example'],
  },
  tabs: {
    MainTab: {
      stack: 'MainStack',
    },
    PlaygroundTab: {
      stack: ['Playground'],
    },
    SettingsTab: {
      stack: ['Settings'],
    },
  },
  modals: {
    ExampleModal: 'ExampleModalStack',
  },
  root: 'Tabs', // 'Tabs' by default; takes also any stack name as a value
});

export type RootStackParamList = {
  // tabs
  Tabs: {
    MainTab: {
       Main: <props>,
       Example: <props>,
    },
    PlaygroundTab: {
      Playground: <props>,
    },
    SettingsTab: {
       Settings: <props>,
    },
  },
  
  // stacks, as you can .pushStack() as well
  ExampleStack: { 
    Example: <props>
  },
  
  // modals
  ExampleModal: {
    Example: <props>
  }
}
```

Hope it helps! And let me know how it works in your case :)
