### ISSUE TITLE
How to pass variable to stack

### ISSUE THREAD

**Issue by Yasir5247** [kanzitelli/expo-starter#41]
@kanzitelli Thank you for the cool updates and navio library. As i'm using navio i have 
few question to ask. so thought to trouble you. 

```
export const navio = Navio.build({
  screens: {
    TabOneScreen: {
      component: TabOneScreen,
      options: () => ({
        title: services.t.do(''),
        ...screenDefaultOptions(),
      }),
    },
    ProductDetailScreen: {
      component: ProductDetailScreen,
      options: {
        headerShown: false,
      },
    },
  },
  HomeStack: {
    screens: ['TabOneScreen'],
    containerOptions: {
      headerShown: true,
      title: '',
    },
  },
  ProductStack: {
    screens: ['ProductDetailScreen'],
    containerOptions: {
      headerShown: true,
      title: 'Product page',
    },
  },
  tabs: {
    AppTabs: {
      content: {
        HomeTab: {
          stack: 'HomeStack',
          options: () => ({
            title: services.t.do(''),
            tabBarIcon: getTabBarIcon('HomeTab'),
          }),
        },
      },
    },
  },
});
```

i have this screen setup and imagine my TabOneScreen had
products and when i click a product im calling this function
navio.stacks.push('ProductStack'). is there anyway to pass the
productId to the ProductDetailScreen and also how to update the title to
product name dynamically?

also in ProductDetailScreen i want to show right
button only if the user is logged just like below. but it doesn't show
what is the best approach here?

```
export const ProductDetailScreen: NavioScreen = observer(() => {
  //navigation buttons
  const configureUI = () => {
    navigation.setOptions({
      headerRight: () =>
        authUser.User.isLogin && (
          <Row>
            <HeaderBImage
              assetName='bookMark'
              assetGroup='product'
              onPress={() => {
                productViolationModalRef.current.open();
              }}
            />
          </Row>
        ),
    });
  };

  useEffect(() => {
    configureUI();
  }, []);

  return ()
});
```

**Comment by kanzitelli** [comment]
Hi @Yasir5247! If you want to pass the params to a Stack, you should use react-navigation's instance `navio.N`:

```
navio.N.navigate('ProductStack', { screen: 'ProductDetailScreen', params: { productId }, });
```

Check out this [issue](https://github.com/kanzitelli/rn-navio/issues/20) for more info.

**Comment by Yasir5247** [comment]
Dear @kanzitelli Thank you as always, I have learned lot from you. 

Here, Let's say i have Tab based application. In the profile tab i have "settings" button. If the user 
presses the "settings" button. i'm taking the user to the "SettingStack". since the first screen of the stack is
"SettingScreen" the app displays the "SettingScreen" screen. 

Now, the problem is while i'm on the "Settings" screen, if i push "CreateCollectionScreen" to the Stack and from the 
"CreateCollectionScreen" if i go back it goes to the "ProfileTab". 

Here what i want to do is while on the "CreateCollectionScreen" if i go back i want it to pop to the first screen of the stack
which is "Settings" screen.

alternatively i could show a modal for each menu in the setting screen. which i really want to avoid, because
i would like get all the possible spaces available to me on certain cases. 

Is this possible?

```
export const navio = Navio.build({
  screens: {
    ...
  },
  stacks: {
    SettingStack: {
      screens: [
        'SettingScreen',
        'CreateCollectionScreen',
        'LanguageScreen',
        'ThemeScreen',
        'ProfileEditScreen',
        'UserLocUpdateScreen',
      ],
      containerOptions: {
        headerShown: true,
        title: 'Settings',
      },
    },
  },
  tabs: {
    AppTabs: {
      content: {
        ProfileTab: {
          stack: 'ProfileStack',
          options: () => ({
            title: 'Profile',
            tabBarIcon: 'icon'
          }),
        },
      },
    },
  },
});
```
